version: '3.8'

services:

  originallanguage_postgresql:
    image: postgres:14.1
    #image: postgres

  #originallanguage_mssql:
  #  image: mcr.microsoft.com/mssql/server:2022-latest

  originallanguage_redis:
    image: redis

  originallanguage_api:
    image: ${DOCKER_REGISTRY-}originallanguageapi
    build:
      context: .
      dockerfile: Systems/Api/OriginalLanguage.Api/Dockerfile
    depends_on:
      - originallanguage_postgresql
      #- originallanguage_mssql
      - originallanguage_redis

  originallanguage_identity:
    image: ${DOCKER_REGISTRY-}originallanguageidentity
    build:
      context: .
      dockerfile: Systems/Identity/OriginalLanguage.Identity/Dockerfile
    depends_on:
      - originallanguage_postgresql
      #- originallanguage_mssql
      - originallanguage_redis
      - originallanguage_api
