version: '3.8'

services:
    originallanguage_postgresql:
        environment:
            - POSTGRES_DB=OriginalLanguage
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=off0zga
        ports:
            - "5432:5432"
        networks:
            - shared_originallanguage_net
        volumes:      
            - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

    originallanguage_redis:
        ports:
            - '6379:6379'
        networks:
            - shared_originallanguage_net
        volumes:      
            - ~/.docker-conf/redis/data/:/data

    originallanguage_api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "80:80"
        env_file:
            - env.api

networks:
    shared_originallanguage_net:
        name: shared_originallanguage_net
        driver: bridge
